server:
  port: 0
  servlet:
    context-path: /drs

platform:
  resilience:
    isHotWarmModel: false

spring:
  application:
    name: dynamic-report-service
    version: '@project.version@'
  profiles:
    active: '@profiles.active@'
    include: core,web,mysql,redis

mybatis-flex:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.luopc.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.luopc: debug
    org.mybatis: debug
    org.springframework.data.mongodb: debug

